config/routes.rb
RailsApiConsumer::Application.routes.draw do
  resources :oauth_consumers do
    member do
      get :callback
      get :callback2
      match 'client/*endpoint' => 'oauth_consumers#client'
    end
  end

  root :to => "welcome#index"

  devise_for :users

end

app/models/consumer_token.rb
#app/models/consumer_token.rb
require 'oauth/models/consumers/token'

class ConsumerToken < ActiveRecord::Base
  include Oauth::Models::Consumers::Token

  # You can safely remove this callback if you don't allow login from any of your services
  before_create :make_user

  # Modify this with class_name etc to match your application
  belongs_to :user

  private

  def make_user
  	logger.info "ConsumerToken make_user"

    self.user ||= begin
      User.new {}
      user.save(:validate => false)
    end
  end
end

app/models/test_service_token.rb
class TestServiceToken < ConsumerToken
	
	TEST_SERVICE_SETTINGS={
		:site => Rails.application.config.test_api_location,
		:request_token_path => "/oauth/request_token",
		:access_token_path => "/oauth/access_token",
		:authorize_path => "/oauth/authorize"
	}
	 
	def self.consumer(options={})
		@consumer ||= OAuth::Consumer.new(credentials[:key], credentials[:secret], TEST_SERVICE_SETTINGS.merge(options))
	end
 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :provider, :uid, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_one  :test_service, :class_name=>"TestServiceToken", :dependent=>:destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/oauth_consumers_controller.rb
require 'oauth/controllers/consumer_controller'

class OauthConsumersController < ApplicationController
  include Oauth::Controllers::ConsumerController
  # Replace this with the equivalent for your authentication framework
  # Eg. for devise
  #
  #   before_filter :authenticate_user!, :only=>:index
  #before_filter :login_required, :only=>:index

  before_filter :authenticate_user!

  def index
    @consumer_tokens=ConsumerToken.all :conditions=>{:user_id=>current_user.id}
    @services=OAUTH_CREDENTIALS.keys-@consumer_tokens.collect{|c| c.class.service_name }

    logger.info "services.first" + @services.first.inspect

    # Bundle more information about the services for display on the index page
    @service_details = []
    @connected_service_details = []

    # Services contains a list of services that the user hasn't connected, if there's nothing in this list,
    # don't construct the service details node

    if @services.first
      @service_details.push({ "name" => "test_service", "site" => Rails.application.config.test_api_location, "token" => @consumer_tokens.first })
    else
      @connected_service_details.push({ "name" => "test_service", "site" => Rails.application.config.test_api_location, "token" => @consumer_tokens.first })
    end

    logger.info "service_details" + @service_details.inspect
    logger.info "connected_service_details" + @connected_service_details.inspect
  end

  def show
    @consumer_tokens=TestServiceToken.all :conditions=>{:user_id=>current_user.id}
    logger.info TestServiceToken.inspect

    if @consumer_tokens.first
      @token = @consumer_tokens.first.client

      #logger.info @token.inspect
    else
      super
    end

  end

  def callback

    begin               
      super
    rescue => e
      #puts "Error during processing: #{$!}"
      #puts "Backtrace:\n\t#{e.backtrace.join("\n\t")}"
      raise
    end
  	
  end

  def client
    super
  end


  protected

  # Change this to decide where you want to redirect user to after callback is finished.
  # params[:id] holds the service name so you could use this to redirect to various parts
  # of your application depending on what service you're connecting to.
  def go_back
    redirect_to root_url
  end

  # The plugin requires logged_in? to return true or false if the user is logged in. Uncomment and
  # call your auth frameworks equivalent below if different. eg. for devise:
  #
  def logged_in?
    user_signed_in?
  end

  # The plugin requires current_user to return the current logged in user. Uncomment and
  # call your auth frameworks equivalent below if different.
  #def current_user
  #  current_person
  #end

  # The plugin requires a way to log a user in. Call your auth frameworks equivalent below
  # if different. eg. for devise:
  #
  def current_user=(user)
    sign_in(user)
  end

  # Override this to deny the user or redirect to a login screen depending on your framework and app
  # if different. eg. for devise:
  #
  def deny_access!
    #raise Acl9::AccessDenied
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	
  	if current_user
	  	@consumer_tokens=TestServiceToken.all :conditions=>{:user_id=>current_user.id}
	    

	    @token = @consumer_tokens.first

	    if @token
	    	@client = @token.client


				#logger.info "Diag: " + @client.consumer.http.inspect

	    	@client.consumer.http.set_debug_output $stderr
	    	@response = @client.get("/api/v2/users")
	    	@data = @response.body

		  	logger.info "private data: " + @response.inspect
		  end
		end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsApi Consumer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
    	<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </a>
    	<a class="brand" href="/">Craigs Rails API Client</a>

      <div class="nav-collapse">
          <ul class="nav">
              <li>
                  <%= link_to 'Home',  "#" %>
              </li>
              <li>    
                  <%= link_to 'About',  "#" %>
              </li>
          </ul>
          <ul class="nav pull-right">
	          <% if user_signed_in? %>
	            <li><%= link_to "Accounts", oauth_consumers_path %></li>
	            <li><%= link_to "Edit Profile", "#" %></li>
	            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
	          <% else %>
	        		<li><%= link_to "Login", new_user_session_path %></li>
	          <% end %>
          </ul>
      </div>
	</div>

	<div class="container">

		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
		<% end %>
		
		<%= yield %>
		
		<div class="footer">
		  <small>
		    by <%= link_to "Craig Edmunds", "http://twitter.com/craigtech" %>
		  </small>
		</div>
	</div>

</body>
</html>

app/views/oauth_consumers/index.html.erb
<h1>Services</h1>

<% if @connected_service_details.empty? %>
  <p>
    You are currently not connected to any external services.
  </p>
<% else %>
  <p>
    You are connected to the following services:
  </p>
  <ul>
    <% @connected_service_details.each do |service| %>
      <li>
        <%= link_to service["name"].to_s.humanize + " [" + service["site"] + "]", oauth_consumer_path(service["token"].class.service_name) %>
      </li>
    <% end %>
  </ul>
<% end %>

<% unless @service_details.empty? %>
<h3>You can connect to the following services:</h3>
<ul>
  <% @service_details.each do |service| %>
    <li>
      <%= link_to service["name"].to_s.humanize + " [" + service["site"] + "]", oauth_consumer_path(service["name"]) %>
    </li>
  <% end %>
</ul>
<% end %>

app/views/oauth_consumers/show.html.erb
<h1>You are connected to <%=params[:id].humanize%></h1>

<h2>Consumer token</h2>

<p>
  <strong>Consumer Key:</strong>
  <code><%= @token.consumer.key %></code>
</p>
<p>
  <strong>Consumer Secret:</strong>
  <code><%= @token.consumer.secret %></code>
</p>
<p>
  <strong>Token:</strong>
  <code><%= @token.token %></code>
</p>
<p>
  <strong>Token secret:</strong>
  <code><%= @token.secret %></code>
</p>
	
<% form_tag oauth_consumer_path(params[:id]),:method=>:delete do %>
  <%=submit_tag "Disconnect" %>
  or
  <%=submit_tag "Reconnect" %>
  if you experienced a problem.
<% end %>

app/views/welcome/index.html.erb
<div class="center hero-unit">
    <h1>Welcome! </h1>
    <p>to <%= link_to 'OAuth client',  "#" %>
     </p>
   	<% unless user_signed_in? %>
    <p> <%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %> </p>
    <% end %>
</div>

<% if @data %>
	<p> <%= @data %> </p>
<% end %>

<p>Find me in app/views/welcome/index.html.erb</p>